# database
spring:
  #security
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 693779976943-29nocg5vr041lva4a0colrlmm1b813j8.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
