spring:
  profiles:
    group:
      local:
        - local
        - secret
      prod :
        - secret
        - db
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL57Dialect
      format_sql: true
      default_batch_fetch_size: 100
    generate-ddl: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
  devtools:
    livereload:
      enabled: 'true'


# server
server:
  servlet:
    encoding:
      force: 'true'
      charset: UTF-8
      enabled: 'true'
    contextPath: /
  port: '8081'
build:
  date: '@build.date@'

# log
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
      apache:
        tiles: INFO
      hibernate:
        SQL: DEBUG
    root: INFO
    com:
      samsung:
        security: DEBUG
  file:
    name: ./ssafy-web.log

# jwt token
jwt:
  access-token-props:
    secret: adsjkQWFRaeiasjodfiwAWeeifjaSDOFJaiewAEWgIREAjORaerjAOESJOgDASIKFJIAJqiojuerfiAE
    expiration-time-milli-sec: '10800000'
  refresh-token-props:
    expiration-time-milli-sec: '864000000'
    secret: ZqefBscadfsGjaiADFSGaoGHdsjjsDFksjgDskdjgDjgHJmdSlzLfjbhikjaqWSogvjdsjzUEvlkvvhnDFGVnkfa==
---
# local only
spring.config.activate.on-profile: local
# database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sapiens
    password: sapiens
    url: jdbc:mysql://localhost:3306/togedocs?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
  data:
    mongodb:
      user: sapiens
      password: sapiens
      host: localhost
      port: 27017
      database: togedocs
      uri: mongodb://localhost:27017/togedocs

  #security
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 693779976943-29nocg5vr041lva4a0colrlmm1b813j8.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

